### ISSUE TITLE
Criar o rodapé do site

### ISSUE THREAD

**Issue by lucolborges** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t6-pmv-ads-2024-1-e5-ecovet#51]

**Comment by carolinamendescontato** [comment]
criação do footer  (https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t6-pmv-ads-2024-1-e5-ecovet/tree/feature/front/footer )
